### ISSUE TITLE
kube-state-metrics prometheus-k8s relate fails

### ISSUE THREAD

**Issue by srebala** [canonical/prometheus-k8s-operator#111]
Hi

when i run below getting no relations found
![image](https://user-images.githubusercontent.com/80451906/130780738-babc99cd-99cd-4b28-9027-5ab4a9979a6e.png)

here is the list of applications on microk8s+juju, pl suggest if i m missing something
![image](https://user-images.githubusercontent.com/80451906/130780852-6b985a47-3382-4768-a7b6-2f2a2dafea9f.png)

**Comment by balbirthomas** [comment]
An PR for an update to Kube State Metrics that makes it work with current release of Prometheus charm is [available here](https://github.com/charmed-kubernetes/kube-state-metrics-operator/pull/4).

**Comment by simskij** [comment]
Compatibility is there from the COS side. As soon as kube-state-metrics is rereleased this should work as expected.
