### ISSUE TITLE
Update the CONTRIBUTING doc with the new JujuTopology terminology

### ISSUE THREAD

**Issue by sed-i** [canonical/prometheus-k8s-operator#152]
This change needs to be reflected in the "code overview" section of the Contributing docs.

_Originally posted by @balbirthomas in https://github.com/canonical/prometheus-operator/pull/149#discussion_r735527809_

- [ ] identifier
- [ ] scrape_identifier
- [ ] promql_labels

**Comment by Abuelodelanada** [comment]
DONE
