### ISSUE TITLE
Pending cleanups for integration tests

### ISSUE THREAD

**Issue by balbirthomas** [canonical/prometheus-k8s-operator#156]
1. Provide a clean up routine that removes copied over Prometheus library file. Perhaps also create and delete the library file directory.
2. Move assert for Prometheus is ready into test code rather than in helper file.
3. Explore if model reset can be done with a test scoped autouse test fixture.
4. Gather consensus on if all tests should abort on fail, none of them should or some of them should.

**Comment by simskij** [comment]
> Gather consensus on if all tests should abort on fail, none of them should or some of them should.

My gut feeling tells me that none of them should. We still want to know if any other tests are failing as well, no?
