### ISSUE TITLE
Get rid of the implicit assumption that this charm only has one unit

### ISSUE THREAD

**Issue by simskij** [canonical/prometheus-k8s-operator#173]
> Seems like this check could be handy in other charms.
That being said, iirc, this charm implicitly assumes in several places there is only one unit.

_Originally posted by @sed-i in https://github.com/canonical/prometheus-operator/pull/147#discussion_r753562148_

**Comment by mmanciop** [comment]
Yeah well, to do this we must have an ingress charmed operator that allows to expose each Prometheus unit separately :-)

**Comment by dstathis** [comment]
We need to verify if this is still an issue.
