### ISSUE TITLE
A Growing list of Integration test cases

### ISSUE THREAD

**Issue by balbirthomas** [canonical/prometheus-k8s-operator#184]
The purpose of this ticket is to create a growing list of Integration test cases for the Prometheus charm.

1. Test Prometheus can recover from a broken config upon refresh. Suggested steps are
     - In a Metrics Provider charm introduce an invalid alert rule
     - Relate the invalid alert rule charm to Prometheus. Prometheus charm will go into blocked state.
     - Fix alert rule and redeploy Metrics Provider . Now check blocked status is removed.
     - Test behaviour of Prometheus with and without ingress.

**Comment by mmanciop** [comment]
> Test behaviour of Prometheus with and without ingress

1. Try to use the PromQL API to fire queries based on data and we put into Prometheus through remote-write or scrape and validate the result with and without ingress

**Comment by rbarry82** [comment]
The alert rule cases are already very heavily unit testing, and integration testing doesn't buy us anything there (especially with the changes to charmcraft part caching which caused issues with `loki-tester` and the write/remove functions in my integration test PR when you try to dunamically modify them).

Ingress is [already covered](https://github.com/canonical/prometheus-k8s-operator/blob/main/tests/integration/test_ingress_with_traefik_k8s.py).

The linked PR cover almost every case we'd possibly want to get from this issue which is not already present.
