### ISSUE TITLE
Investigate whether the endpoint update of remote write could be delegated to library code

### ISSUE THREAD

**Issue by simskij** [canonical/prometheus-k8s-operator#195]
Can this be delegated to library code?

_Originally posted by @sed-i in https://github.com/canonical/prometheus-k8s-operator/pull/147#discussion_r768711546_

**Comment by rbarry82** [comment]
It already is (via the method). In the past year, we have come to realize the need to actually have _some_ ability to trigger changes ad-hoc to avoid event ordering problems (when an event is handled after an object has already been instantiated in the constructor).

Until when/if we actually pass closures into constructors for all data which is possibly dynamic, closing for now.
