### ISSUE TITLE
Refactor time based flaky integration tests

### ISSUE THREAD

**Issue by balbirthomas** [canonical/prometheus-k8s-operator#197]
## Integration tests may fail if Github workflow is slow

A recent commit introduced tests that use an extended `timeout` value. These timeout values were extended because, when Github workflows are slow the test fails sporadically. However the choice of a timeout value is arbitrary. Hence the tests may still fail if github gets even slower. The purpose of this ticket is to refactor these tests so that they are not timeout based. The tests in question are

1. https://github.com/canonical/prometheus-k8s-operator/blob/main/tests/integration/test_kubectl_delete.py
2. https://github.com/canonical/prometheus-k8s-operator/blob/main/tests/integration/test_upgrade_charm.py

**Comment by balbirthomas** [comment]
Discussion on this problem is [here](https://github.com/canonical/prometheus-scrape-config-k8s-operator/pull/5#discussion_r781360930)

**Comment by sed-i** [comment]
The "extended timeout" existed before the two new tests
https://github.com/canonical/alertmanager-k8s-operator/blob/main/tests/integration/test_charm.py

The tests themselves are not flaky. I suggest changing the title of the PR.

**Comment by balbirthomas** [comment]
> The tests themselves are not flaky. I suggest changing the title of the PR.

Thanks for highlighting the additional test that may need a rethink. Any test which uses an arbitrary timeout can be flaky. I think we should explore other option within the pytest-operator and python-libjuju APIs to see if we can avoid these magic numbers.
