### ISSUE TITLE
Change return type of `_remote_write_address` to strictly string

### ISSUE THREAD

**Issue by sed-i** [canonical/prometheus-k8s-operator#206]
> This is bad practice for the following reason -  An empty string is false in a boolean context. Hence the return type does not need to be an optional string, it can always be a string. This ensures every method always has a single, unique, well defined return type. Failure to ensure single unique return types in general is bad practice because it prevents composition of functions i.e f(g(x)) etc.

_Originally posted by @balbirthomas in https://github.com/canonical/prometheus-k8s-operator/pull/205#discussion_r787556937_

> this means it should return `""`, not `None`, and the constructor for `PrometheusRemoteWriteProvider` should take `endpoint_address: Optional[str] = ""`. 
>
> It doesn't otherwise change the logic.

_Originally posted by @rbarry82 in https://github.com/canonical/prometheus-k8s-operator/pull/205#discussion_r787637435_

> To elaborate on my points above consider what happens if some other methods that invokes this one writes something like this
>```
>if len(returned_address) > 0:
>    blah blah blah 
>```
>If you always returned a string this would not blow up. It does blow up because you return `NoneType`.
>On the other hand if the invoking method did
>```
>if returned_address:
>    blah blah blah
>```
>It is indeed fine even with NoneType but it will also be fine with empty string instead of NoneType.
>Which solution "makes your code easy to use".

_Originally posted by @balbirthomas in https://github.com/canonical/prometheus-k8s-operator/pull/205#discussion_r788077614_

**Comment by sed-i** [comment]
@balbirthomas I am still not convinced `""` is better than `None`. Could you provide a reference discussing what is more idiomatic?
1. the semantics of this function is "give me ip address", not "give me str repr of the ip address". for this reason `len(returned_address)` makes no sense and should probably raise if used inappropriately.
1. users would see it returns Optional so they'd know to expect it
1. None gives the advantage of getting an exception if misused, whereas "" could be used mistakenly. "Errors should never pass silently" and I see no reason to explicitly silence it.

**Comment by balbirthomas** [comment]
> @balbirthomas  Could you provide a reference discussing what is more idiomatic?

Consistent return types is not just Python specific, it applies to most programming languages. My opinion is based on books read eons ago and a lot of pain experienced over recent past. I can dig out some reference if I can pull out the time.

>     1. the semantics of this function is "give me ip address", not "give me str repr of the ip address". for this reason `len(returned_address)` makes no sense and should probably raise if used inappropriately.

What is an "IP address"  ? Isn't it a string with 4 natural numbers separated by dots. If a user writes a function to validate the returned IP address using function calls to check its length, then number of dots in it  etc, what happens ?

>     2. users would see it returns Optional so they'd know to expect it

User can also see the doc string that could  *also* explain not just that a "falsy" value can be returned but also **when** and **why**. That information is **not available from a type signature**. 

>     3. None gives the advantage of getting an exception if misused, whereas "" could be used mistakenly. "Errors should never pass silently" and I see no reason to explicitly silence it.

If you want to raise an error when you are not able to find an IP address then why not raise an exception. How does returning a "" lead to silencing and error any more than returning a NoneType.  Both are "falsy" values. **The claim that `NoneType` will raise an exception but empty string will not is a bad one**. Here is the reason why. NoneType will raise an exception of and **unknown type** at an **unpredictable place** in the code. On the other hand if you choose not to "silence the error" you can raise an documented exception of a **known type**.
