### ISSUE TITLE
Wrong links and name in charmcraft-prometheus in chamhub.io

### ISSUE THREAD

**Issue by erik78se** [canonical/prometheus-k8s-operator#221]
I'm trying to deploy charmcraft-prometheus (VM version) from charmhub.io (stable 3)

Multiple issues:

1. The "URL" in the docs for the VM machine class charm points to this repo. So, I don't know if this issue belongs here, but its the reference in charmhub.io

The URL should point to the correct repo?

2. The documentation claims it is for Kubernetes, where it clearly is for VM charm (See screenshot)
![image](https://user-images.githubusercontent.com/850603/152127728-abb1e4fa-95d9-4ff0-bc2d-6322962e5e98.png)

3. The charm errors when deploying on AWS. (See [separate issue](https://github.com/canonical/prometheus-k8s-operator/issues/222))

**Comment by simskij** [comment]
As mentioned in [#57](https://github.com/canonical/grafana-k8s-operator/issues/57), that is not the COS Lite charm. The actual charm is available at https://charmhub.io/prometheus-k8s
