### ISSUE TITLE
`_apply_label_matcher` creates an unwarranted file on filesytsem

### ISSUE THREAD

**Issue by sed-i** [canonical/prometheus-k8s-operator#223]
The test `test_consumer_returns_alerts_rules_file` calls 
```
rules_file = self.harness.charm.prometheus_consumer.alerts()
```
which eventually calls `_apply_label_matcher` results in a file named `0.12` created in the charms folder, with the following contents:
```
process_cpu_seconds_total{juju_application="consumer-tester",juju_model="None",juju_model_uuid="f2c1b2a6-e006-11eb-ba80-0242ac130004"}
```
"0.12" happens to be the string after ">" in the alert rule. Seems like this is executed as a shell script.
```
./tests/unit/test_endpoint_consumer.py
69:                    "expr": "process_cpu_seconds_total > 0.12",
```

**Comment by rbarry82** [comment]
```python
result = subprocess.run(" ".join(cmd), check=False, stdout=subprocess.PIPE, shell=True)
```

**shell=True**

🚨🚨 wait until it's passed a rule with `expr: pass; rm -rf /` 🚨🚨
