### ISSUE TITLE
Prometheus enters blocked state when the pod churns

### ISSUE THREAD

**Issue by dstathis** [canonical/prometheus-k8s-operator#237]
### Bug Description

Title says it all

### To Reproduce

1. deploy prometheus-k8s
2. `kubectl delete pod prometheus-0`

### Environment

juju: 2.9.25-ubuntu-amd64
microk8s: v1.23.3
os: Ubuntu 20.04.4 LTS

### Relevant log output

```shell
prom/0*   blocked   idle   10.1.250.214         Failed to load Prometheus config
```

**Comment by PietroPasotti** [comment]
Also happened to me while scaling up 1 --> 4 units.

**Comment by balbirthomas** [comment]
Ok. Tried to reproduce it today with latest beta release (revision 20) using both ways described above but failed to reproduce it. Tried the `delete pod` way a couple of more times. Does this happen every time ?

**Comment by dstathis** [comment]
I thought it did. It also happens when you reboot the microk8s node (on prometheus built from main).

Additionally, I noticed that Prometheus remains with that status but is in fact running at that point. I think this likely implies that this is a bug with ordering of hooks not setting active status correctly.

**Comment by balbirthomas** [comment]
By "reboot the microk8s" do you mean `microk8s stop` and then `microk8s start` ?

**Comment by balbirthomas** [comment]
@dstathis Is this issue still reproducible. I have previously tried to reproduce this and failed to do so. Have you seen it recently ? Shall we close this ticket ? Shall we try to reproduce it again ?

**Comment by dstathis** [comment]
I tried to reproduce this with Prometheus from edge and was not able to.
