### ISSUE TITLE
Simplify JujuTopology class interface

### ISSUE THREAD

**Issue by balbirthomas** [canonical/prometheus-k8s-operator#240]
### Bug Description

The `JujuTopology` class and its use within this charm has become complex and difficult to understand. In particular this complexity stems from the following
- Multiple methods that do similar things. For example `as_dict()`, `as_promql_label_dict()`, `promql_labels()` or `JujuTopology.identifier()` and `ProviderTopology.scrape_identifier()`
- `MetricsEndpointProvider` sets topology relation data without `juju_` prefix but topology information is always used with `juju_` prefix.
- Possibly also Juju model UUID is used in two ways truncated to 7 digits or not.

There may be other latent issues.

### To Reproduce

Not Applicable : This is a code clean up issue.

### Environment

Not Applicable: This is a code cleanup issue

### Relevant log output

```shell
Not Applicable: This is a code cleanup issue
```

**Comment by balbirthomas** [comment]
For an example of the impacts of this complexity see [this message in PR239](https://github.com/canonical/prometheus-k8s-operator/pull/239#issuecomment-1061695510)

**Comment by simskij** [comment]
Once https://github.com/canonical/observability-libs/pull/11 lands, we'll migrate to using that.
