### ISSUE TITLE
MetricsEndpointProvider should not add Juju unit charm labels by default

### ISSUE THREAD

**Issue by balbirthomas** [canonical/prometheus-k8s-operator#246]
### Bug Description

At present `MetricsEndpointProvider` adds `juju_unit` and `juju_charm` labels to alert rules. These to labels should not be added to the alert rule. However if they were already present in an alert rule they must not be removed.

### To Reproduce

1. Follow the deployment steps shown in the README file for the [cos-proxy-operator](https://github.com/canonical/cos-proxy-operator)
2. Browse to the Prometheus dashboard and you should see alert rules with `juju_unit` and `juju_charm` labels.

### Environment

As described in the README of [cos-proxy-operator](https://github.com/canonical/cos-proxy-operator)

### Relevant log output

```shell
A sample flawed alert rule is shown below

name: CPU_Usage
expr: cpu_usage_idle{group="promoagents-juju",is_container!="True"} < 10
for: 5m
labels:
cloud: juju
juju_application: telegraf
juju_model: reactive
juju_model_uuid: 98b85b1
juju_unit: telegraf/1
override_group_by: host
severity: page
annotations:
description: Host {{ $labels.host }} has had <  10% idle cpu for the last 5m
summary: Host {{ $labels.host }} CPU free is less than 10%
```
```


### Additional context

_No response_

**Comment by mmanciop** [comment]
For the avoidance of doubt, we must:

1. We can (SHOULD?) add the juju_charm to the alert rule labels, as it is useful context in a notification (“oh cassandra is misbehaving”)
2. We MUST NOT add the juju_unit label to the alert rule
3. We MUST NOT add matchers to the alert rule’s expression via PromQL transformer for juju_charm

**Comment by dstathis** [comment]
This is done. Closing.
