### ISSUE TITLE
Improve _pod_ip property

### ISSUE THREAD

**Issue by Abuelodelanada** [canonical/prometheus-k8s-operator#251]
If `self.model.get_binding("prometheus-peers").network.bind_address` returns something that evaluates to `False` (`None`, or `""`) this property will return `None` but its signature indicates that returns a string.

https://github.com/canonical/prometheus-k8s-operator/blob/316f9c364637161750276b55356678b93bbc8fb8/src/charm.py#L357

**Comment by mmanciop** [comment]
So, you mean the property is _falsy_, and that as type we should rather make it `Optional[str]`?

**Comment by balbirthomas** [comment]
It is just as simple and perhaps better to to add and `else` clause so that the property returns and empty string when the `bind_address` is `None`.

``` python
    def _pod_ip(self) -> str:
        """Returns the pod ip of this unit."""
        if bind_address := self.model.get_binding("prometheus-peers").network.bind_address:
            return str(bind_address)
        else:
            return ""
``
