### ISSUE TITLE
Update status should do a health check

### ISSUE THREAD

**Issue by balbirthomas** [canonical/prometheus-k8s-operator#258]
At present, the Prometheus charm update status hook does not really validate the healthy status of the Prometheus workload. This may be useful functionality to have.

**Comment by balbirthomas** [comment]
Assigned to @dstathis since this is alread work in progress in [PR265](https://github.com/canonical/prometheus-k8s-operator/pull/265). 

@dstathis I hope you have seen @jnsgruk comment on your PR.

**Comment by simskij** [comment]
We've decided to not proceed with this at this point. Once pebble health checks and liveliness checks allow for emitting events, we'll likely revisit this.
