### ISSUE TITLE
Remove all references to `patch_network_get`

### ISSUE THREAD

**Issue by sed-i** [canonical/prometheus-k8s-operator#294]
Now that we move to `socket.getfqdn` in favor of `bind_address`, mocking `network_get` would eventually become unnecessary.

Depends on:

- #293 
- all libs to drop bind_address
- fetch-lib

**Comment by balbirthomas** [comment]
I think this issue is no obsolete in view of merged [PR 331](https://github.com/canonical/prometheus-k8s-operator/pull/331) and  [Issue 329](https://github.com/canonical/prometheus-k8s-operator/issues/329), hence I think this issue may be closed.
