### ISSUE TITLE
Add configurability for Prometheus storage size

### ISSUE THREAD

**Issue by Abuelodelanada** [canonical/prometheus-k8s-operator#296]
Investigate:

1.  how juju storage works
2. how a Juju administrator can limit storage usage by Prometheus
3. whether Prometheus correctly throws away the oldest datapoints when running out of storage

https://prometheus.io/docs/prometheus/1.8/storage/#settings-for-very-long-retention-time

new version with stable storage flags: https://github.com/prometheus/prometheus/releases/tag/v2.29.0-rc.1

OK we can certainly add storage.tsdb.retention.size .

**Comment by sed-i** [comment]
`storage.tsdb.retention.size` is WIP in #295. Take a look?
