### ISSUE TITLE
Support both fixed sizes and percentages for retnetion size limit

### ISSUE THREAD

**Issue by sed-i** [canonical/prometheus-k8s-operator#298]
> Would it be possible to support both fixed sizes and percentages? If so, I think that would be killer.
> _Originally posted by @simskij in https://github.com/canonical/prometheus-k8s-operator/issues/295#issuecomment-1149992726_

Depends on #295.

**Comment by simskij** [comment]
Given that the provided fixed size value suddenly could become invalid without any user interference, we've opted to only support percentages for now.
