### ISSUE TITLE
Provider should raise if multiple jobs are declared but no job suffixes are set

### ISSUE THREAD

**Issue by simskij** [canonical/prometheus-k8s-operator#320]
### Enhancement Proposal

If a charm author tries to declare more than one job while instantiating the `MetricsEndpointProvider`, they need to set a job suffix. If they don't, the library should put the provider in an error status to make sure they fix it **prior** to releasing a new version of the charm.

**Comment by rbarry82** [comment]
Considering #427 and increasing complexity of use cases, this is something we should do.

Probably, we could log a warning. If `len(jobs) > 1`, we could iterate over them, find the ones which don't have a `job_name` set, automatically create one (based on the information we do have, like the charm name, scrape endpoint, etc), and log a warning. It still works, but a warning-level nag is hopefully high enough that it will be noticed.

**Comment by simskij** [comment]
Isn't it better we just block or error so the charm dev fixes it during development time, rather than having the user notice at runtime when trying to relate them together?

**Comment by rbarry82** [comment]
Sure, it's better, but it's perfectly possible for dynamically created jobs which are [appended from the callable](https://github.com/canonical/prometheus-k8s-operator/blob/main/lib/charms/prometheus_k8s/v0/prometheus_scrape.py#L1703) to violate this constraint at runtime even after relating when some other action (adding a new LXD unit, for example) mutates the list.

**Comment by simskij** [comment]
Fair point!

**Comment by simskij** [comment]
Issue has been stale for a year and a half, and it's relevance today is thus debatable. Closing for now. Create a new issue or reopen this one if this is still affecting you.
