### ISSUE TITLE
README.md incorrectly suggests to use the nginx ingress

### ISSUE THREAD

**Issue by simskij** [canonical/prometheus-k8s-operator#338]
### Bug Description

> Access to Prometheus from outside the Kubernetes cluster can be provided via ingress relation with the [Nginx Ingress Integrator](https://charmhub.io/nginx-ingress-integrator). This relation is experimental, and there is a chance the charm will evolve to use some other mechanism to be reachable from the outside of the hosting Kubernetes cluster.

### To Reproduce

N/A

### Environment

N/A

### Relevant log output

```shell
N/A
```

### Additional context

Should instead suggest traefik-k8s's ingress-per-unit relation

**Comment by sed-i** [comment]
This was fixed in https://github.com/canonical/prometheus-k8s-operator/commit/102bfa4820eb3832923c7b2654e9e269bfa3a3ae.
