### ISSUE TITLE
Improve cognitive ease of alert rules filename

### ISSUE THREAD

**Issue by sed-i** [canonical/prometheus-k8s-operator#345]
### Enhancement Proposal

Currently, the amalgamated alert rules filename that gets written to prom's filesystem looks like this:
```
juju_cos2_f2dc1aa0-de3b-4a7a-8636-2d56c0967dd8_am.rules
```
Specifically, the model name and app name are separated by the model uuid. This is inconvenient. It would be easier to read this if human-readable portions of the topology were next to each other, e.g. `[prefix]_[uuid]_[model]_[app]`:
```
juju_f2dc1aa0-de3b-4a7a-8636-2d56c0967dd8_cos2_am.rules
```
This way a human reader can get easily used to having the most valuable information payload at the end.

**Comment by simskij** [comment]
Are there any possible ripple-effects we might need to take into consideration here? I don't think we use the filename anywhere, but we should make sure that is the case

**Comment by simskij** [comment]
There is too little value in this change at the moment to warrant putting development time into it.
