### ISSUE TITLE
Add support for remote writing from one Prometheus to another

### ISSUE THREAD

**Issue by simskij** [canonical/prometheus-k8s-operator#353]
### Enhancement Proposal

We need to support use cases where users want to tier their Prometheus deployments to avoid excessive pressure. By adding `send-remote-write` to Prometheus, and remote writing whatever we receive, we've effectively accomplished this.

**Comment by beliaev-maksim** [comment]
> Note: reopen and append #410 when receive customer request with requirements.
> For discussion around the feature please see #376

**Comment by PietroPasotti** [comment]
it was added at some point (#376) but it was later removed (when?, by whom? why?)
does @simskij remember? Or maybe @beliaev-maksim?
