### ISSUE TITLE
If a push fails, prometheus may never be reload even though config changed (theoretical edge-case)

### ISSUE THREAD

**Issue by sed-i** [canonical/prometheus-k8s-operator#369]
If some files were pushed but others failed, when _configure re-enters then `should_reload` may be false without prometheus ever reloading.

https://github.com/canonical/prometheus-k8s-operator/blob/b4c0fd631a8bfbeb7d22b9b6f157f8f25cefc6f6/src/charm.py#L292-L304

**Comment by PietroPasotti** [comment]
we should probably let the error bubble up in this case, assuming the caller checked `container.can_connect` before this happens. Error state seems appropriate because this really shouldn't happen.

**Comment by simskij** [comment]
Issue has been stale for more than a year, and it's relevance today is thus debatable. Closing for now. Create a new issue or reopen this one if this is affecting you.
