### ISSUE TITLE
alert rules disappear if k8s cluster gets rebooted

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/prometheus-k8s-operator#386]
### Bug Description

During testing microk8s cluster went down. Due to some issue cluster entered CrashLoopBackOff and juju restarted it. Once units went up again, alert rules were empty

### To Reproduce

restart k8s cluster with deployed prometheus
check alert rules

### Environment

-

### Relevant log output

```shell
-
```

**Comment by sed-i** [comment]
This is probably because the config hash is in StoredState on the controller.
As discussed, storing the hash inside the workload container may improve resilience.
