### ISSUE TITLE
Prometheus_scrape needs to allow path per unit

### ISSUE THREAD

**Issue by dstathis** [canonical/prometheus-k8s-operator#393]
### Bug Description

If a workload charm is using ingress_per_unit, It will have a different metrics path for each unit. Currently metrics path is a global option for the whole application.

### To Reproduce

-

### Environment

-

### Relevant log output

```shell
-
```

**Comment by sed-i** [comment]
I wonder how you encountered this. I thought #373 et. al. addressed exactly this.
