### ISSUE TITLE
Check if prometheus_scrape provider is compatible with machine charms.

### ISSUE THREAD

**Issue by dstathis** [canonical/prometheus-k8s-operator#403]
https://github.com/canonical/prometheus-k8s-operator/blob/0a22b74bfde434f9a2b19635abc2fb507d664ce2/lib/charms/prometheus_k8s/v0/prometheus_scrape.py#L1543-L1561

This block in `MetricsEndpointProvider` may not be compatible with machine charms. It depends on whether `_charm.meta.containers` raises an exception or not. If so, some code change will be needed.

**Comment by zmraul** [comment]
I'm currently testing this situation trying to have a cross-model relation with a `node_exporter`. When deploying a machine charm, the charm gets into an active|idle status. Will update with more info if I find something relevant. ([The charm I'm using](https://github.com/zmraul/db-relations-k8s/tree/vm-minimal))

**Comment by rbarry82** [comment]
This will, [never, ever fail](https://github.com/canonical/operator/blob/a0b3d814168258b798595328543ed9ae668ecb62/ops/charm.py#L1123). In the worst case it's an empty dict with length 0, and we fall though.
