### ISSUE TITLE
Review use of stored state to cache config file hashes

### ISSUE THREAD

**Issue by sed-i** [canonical/prometheus-k8s-operator#418]
> the caching that you're doing seems like you need to push it again on some upgrades, as whenever the pod gets rescheduled then /etc/prometheus/prometheus.yml isn't going to be there
> so it [local storage instead of controller storage; see [ops/880](https://github.com/canonical/operator/issues/880)] actually helps you, because you actually should be pushing on every pebble_ready event

-- @jameinel

Related: #414

**Comment by dstathis** [comment]
We need to investigate how we are storing the hash of our config files. Either carefully confirm that stored state works, write the hash to disk, or run statelessly.
