### ISSUE TITLE
charm_metrics

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/prometheus-k8s-operator#528]
### Enhancement Proposal

We could hack together something analogous to Tempo's charm_tracing: a new `charm_metrics` library, which would talk to a prometheus via remote-write using https://pypi.org/project/opentelemetry-exporter-prometheus-remote-write/

Similar to:
- https://github.com/canonical/loki-k8s-operator/pull/306

**Comment by sed-i** [comment]
Need to figure out:
- What kind of metrics (different from the workload metrics). Perhaps keep it delegated to pebble?
- How to expose - push (remote write) or pull (metrics endpoint)?

**Comment by lucabello** [comment]
@PietroPasotti can you elaborate on this?
