### ISSUE TITLE
Internal url is rendered as the "source" in alerts

### ISSUE THREAD

**Issue by sed-i** [canonical/prometheus-k8s-operator#581]
### Bug Description

> If i go to alertmanager, check an alert and click on the Source button, it will want to take me to `http://prometheus-0.cos.svc.kubernetes.cluster:9090` (or something along those lines), but i have a traefik loadbalancer in front of both alertmanager and prometheus, so i would expect the Source button to take me to `http://$LOADBALANCER_IP/cos-prometheus-0` instead.
>
> The ingress url is there alright, but the command used to launch prometheus points to the internal DNS name
> ```bash
> # kubectl -n cos exec prometheus-0 -c prometheus -- ps uax | grep -oE -- '--web.external-url=[a-z0-9:/\.\-]*'
> --web.external-url=http://prometheus-0.prometheus-endpoints.cos.svc.cluster.local:9090/cos-prometheus-0
> ```
> This comes from charm code:
> ```python
>         route_prefix = urlparse(self.external_url).path.strip("/")
>         external_url = f"{self.internal_url.rstrip('/')}/{route_prefix}".rstrip("/")
> ```
> -- @peterctl

### To Reproduce

traefik - prometheus - alertmanager

### Environment

TBD

### Relevant log output

```shell
N/A
```

### Additional context

We may be able to address this with label rewrite.

**Comment by Abuelodelanada** [comment]
This issue is related to this one: https://github.com/canonical/alertmanager-k8s-operator/issues/206

**Comment by mcarvalhor** [comment]
Please see this workaround that we implemented on IS side (issue is still relevant though):
- https://code.launchpad.net/~mcarvalhor/canonical-terraform-plans/+git/canonical-terraform-plans/+merge/470138
(CTRL+F for "Workaround")
